#!/bin/bash
cd /home/ubuntu/tua.server/node
sudo npm install
sudo chmod 777 -R backend/
cd backend/
sudo npm install
cd /home/ubuntu/tua.server
sudo docker-compose up > /dev/null 2> /dev/null < /dev/null &
