version: 0.0
os: linux
files:
  - source: /backend
    destination: /home/ubuntu/willson/node/backend
  - source: package.json
    destination: /home/ubuntu/willson/node
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
